/*
* Automatically generated by 'ng g ng-alain:plugin icon'
* @see https://ng-alain.com/cli/plugin#icon
*/

import {
  LoginOutline,
  LineChartOutline,
  ProfileOutline,
  DatabaseOutline,
  UnorderedListOutline,
  LogoutOutline,
  SettingOutline,
  CopyrightOutline,
  UserOutline,
  LockOutline,
  ArrowLeftOutline,
  ApartmentOutline,
  OrderedListOutline,
  RollbackOutline,
  RetweetOutline,
  GoldOutline,
  MenuOutline,
  CarOutline,
  SnippetsOutline


} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  LoginOutline,
  LineChartOutline,
  ProfileOutline,
  DatabaseOutline,
  UnorderedListOutline,
  LogoutOutline,
  SettingOutline,
  CopyrightOutline,
  UserOutline,
  LockOutline,
  ArrowLeftOutline,
  ApartmentOutline,
  OrderedListOutline,
  RollbackOutline,
  RetweetOutline,
  GoldOutline,
  MenuOutline,
  CarOutline,
  SnippetsOutline

];
